# Generated by Django 4.0.1 on 2022-05-14 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication_app.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
